#language: node_js
#sudo: false
#addons:
#  apt:
#    packages:
#      - vagrant
install:
  - sudo apt-get update
  - sudo apt-get install libsdl1.2debian
  - sudo apt-get install libvpx1
  - sudo apt-get install dkms


#  - sudo wget -nv http://download.virtualbox.org/virtualbox/4.3.30/virtualbox-4.3_4.3.30-101610~Ubuntu~precise_amd64.deb
#  - sudo dpkg -i virtualbox-4.3_4.3.30-101610~Ubuntu~precise_amd64.deb

  
  - sudo wget -nv http://download.virtualbox.org/virtualbox/5.0.0/virtualbox-5.0_5.0.0-101573~Ubuntu~precise_amd64.deb
  - sudo dpkg -i virtualbox-5.0_5.0.0-101573~Ubuntu~precise_amd64.deb

#  - sudo wget -nv http://download.virtualbox.org/virtualbox/4.1.40/virtualbox-4.1_4.1.40-101594~Ubuntu~precise_amd64.deb
#  - sudo dpkg -i virtualbox-4.1_4.1.40-101594~Ubuntu~precise_amd64.deb
  
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb
  - sudo dpkg -i vagrant_1.7.4_x86_64.deb

  # - sudo apt-get install virtualbox-dkms
  #- sudo apt-get install virtualbox-ose-dkms
  # - sudo apt-get install build-essential
  #- sudo apt-get install linux-headers--2.6.32
  
  # - sudo /etc/init.d/vboxdrv setup
  - sudo VBoxManage --version
  
  
#node_js:
#  - "0.10"
env:
  - TEST_SUITE=lint
before_script:
  - vagrant up
script:
  "sleep 30s ; ./vgr/ping.sh"
