#language: node_js
#sudo: false
#addons:
#  apt:
#    packages:
#      - vagrant
install:
#   - sudo apt-get update
#   - sudo apt-get install ruby
#   - sudo apt-get install vagrant

  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox --fix-missing
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb
  - sudo dpkg -i vagrant_1.7.4_x86_64.deb

#node_js:
#  - "0.10"
env:
  - TEST_SUITE=lint
before_script:
  - vagrant up
script:
  "sleep 30s ; ./vgr/ping.sh"
